Osipov-K-S-lab-1-2
Qui-Gon173/AiSD-2020 pull request #132
Opened 2020-11-12 07:25 UTC by KirillOsipov

2020-11-14 16:34 UTC, Qui-Gon173 approved these changes
Зачтено.

2020-11-14 16:35 UTC, Qui-Gon173 requested changes
Только перенесите пожалуйста вашу папку с лабами в ISTbd-22

2020-11-15 07:42 UTC, KirillOsipov commented
> Только перенесите пожалуйста вашу папку с лабами в ISTbd-22

Здравствуйте. Я не совсем понимаю, как это сделать. То есть мне нужно на локальной копии перенести папки с лабораторными в ISTbd-22, а затем снова закоммитить и создать новый pull request или как-то по-другому?

2020-11-17 06:56 UTC, Qui-Gon173 commented
Практически. Перенесите вашу папку в ISTbd-22 и закоммитьте изменения. Они отобразятся в этом пул реквесте

2020-11-19 18:05 UTC, Qui-Gon173 approved these changes

2020-11-19 18:05 UTC, merged