Uskova A S lab5
Qui-Gon173/AiSD-2020 pull request #136
Opened 2020-11-12 16:01 UTC by U-Aleksandra

2020-11-14 17:02 UTC, Qui-Gon173 requested changes
Код программы идентичен программе Енилова Д.А, за исключением, что вы переименовали переменные value1, value2, count_elements, counter и объявили их в одной строке вместе с i,j. По отчету нет вопросов.

2020-11-15 08:07 UTC, U-Aleksandra commented
мы, наверное, код смотрели с одного сайта:  https://intuit.ru/studies/courses/648/504/lecture/11473?page=1 
мне все равно надо изменить код?

2020-11-17 06:57 UTC, Qui-Gon173 commented
Хм, действительно. Да, перепишите на потоках С++, у вас используются конструкции языка C

2020-11-19 18:11 UTC, Qui-Gon173 requested changes
Замечание также относилось к файловым потокам

2020-11-26 05:00 UTC, Qui-Gon173 approved these changes
Зачтено

2020-11-26 05:01 UTC, merged