Doronkin A N lab 3
Qui-Gon173/AiSD-2020 pull request #162
Opened 2020-11-18 15:53 UTC by Letov1337

2020-11-26 05:03 UTC, Qui-Gon173 requested changes

2020-11-26 05:03 UTC, Qui-Gon173 commented on ISTbd-22/Doronkin A.N/lab3/main.cpp
> +int *Mas2=new int[n];
Использовать глобальные переменные - плохой тон. Используйте локальные переменные и передавайте их в методы.

2020-11-26 13:10 UTC, Letov1337 commented on ISTbd-22/Doronkin A.N/lab3/main.cpp
> +int *Mas2=new int[n];
Исправил.

2020-12-02 15:43 UTC, Qui-Gon173 approved these changes
Зачтено

2020-12-02 15:43 UTC, merged