Тагашев Иван - Lab-5
Qui-Gon173/AiSD-2020 pull request #164
Opened 2020-11-18 18:02 UTC by bastep-ulstu

Лаб 5 cpp+md

2020-11-26 05:07 UTC, Qui-Gon173 commented
Алгоритм реализован верно, но применен неправильно. Нельзя выгружать полностью все данные из файла и потом их сортировать. Сортировка должна проходить с помощью 2 вспомогательный файлов, и у вас в памяти должны быть максимум 2 значения(которые сравниваются). Прочитайте внимательнее источник на интуите. Только не используйте код, который там указан :smiley: При реализации чтения и записи используйте потоки С++.

2020-11-26 05:08 UTC, Qui-Gon173 requested changes
Алгоритм реализован верно, но применен неправильно. Нельзя выгружать полностью все данные из файла и потом их сортировать. Сортировка должна проходить с помощью 2 вспомогательный файлов, и у вас в памяти должны быть максимум 2 значения(которые сравниваются). Прочитайте внимательнее источник на интуите. Только не используйте код, который там указан :smiley: При реализации чтения и записи используйте потоки С++.

2020-11-26 13:34 UTC, v01d-gh commented
> При реализации чтения и записи используйте потоки С++.

Вот это действительно актуальная идея!

2020-12-06 12:36 UTC, Qui-Gon173 approved these changes
Зачтено

2020-12-06 12:37 UTC, merged