EgorovIE-lab5
Qui-Gon173/AiSD-2020 pull request #232
Opened 2020-12-05 22:46 UTC by Doomaykaka

2020-12-06 12:50 UTC, Qui-Gon173 requested changes
Сортировка должна применяться на файлах. Причем все данные выгружать в память нельзя, а только 2 значения за в 1 момент времени. Изучите интуит, там достаточно подробно расписан принцип работы алгоритма

2020-12-06 14:41 UTC, Doomaykaka commented
Хорошо

2020-12-06 19:28 UTC, Doomaykaka commented
Я переправил , реализовал код интуита

2020-12-06 19:28 UTC, Doomaykaka commented
использовал файлы

2020-12-08 16:40 UTC, closed without merging

2020-12-08 16:41 UTC, Qui-Gon173 commented
Исправление замечаний сделано в другом пул реквесте #235