Крахмалюк Д.А. лаб 5
Qui-Gon173/AiSD-2020 pull request #239
Opened 2020-12-07 15:19 UTC by rockaxl3

2020-12-07 18:09 UTC, v01d-gh commented on ISTbd-22/Krakhmalyuk-D-A/lab5/aisd_lab5.cpp
> +		a[i] = rand() % 228;
А что, звучит...

2020-12-07 18:46 UTC, Juggernauff commented on ISTbd-22/Krakhmalyuk-D-A/lab5/aisd_lab5.cpp
> +		a[i] = rand() % 228;
> А что, звучит...

сказочно?..

2020-12-08 17:23 UTC, Qui-Gon173 commented on ISTbd-22/Krakhmalyuk-D-A/lab5/aisd_lab5.cpp
> +		a[i] = rand() % 228;
тут похоже какой-то локальный юмор)

2020-12-08 17:27 UTC, Qui-Gon173 requested changes
Где-то у вас используются потоки C, где-то С++. Используйте только потоки C++.

2020-12-12 15:46 UTC, merged