no message
Qui-Gon173/AiSD-2020 pull request #268
Opened 2020-12-17 10:47 UTC by HerbalTea312

2020-12-18 19:22 UTC, Qui-Gon173 requested changes
Очень хорошо сделано, приятно читать код с комментариями и правильными названиями методов и полей. Поправьте мелкие замечания по наименованию(если не хотите, можете не править). Главное учтите замечание по направлениям.

2020-12-18 19:22 UTC, Qui-Gon173 commented on ISTbd-22/Kuchina A. A/lab8.1/list.h
> +    return count_conteiner;};
`count_conteiner` Маленькая очепятка, правильно `count_container`) лучше переменную назвать size или elements_count.

2020-12-18 19:22 UTC, Qui-Gon173 commented on ISTbd-22/Kuchina A. A/lab8.1/list.h
> +unsigned long mid_value();//среднее значение всех значений элементов
вместо mid лучше написать average

2020-12-18 19:22 UTC, Qui-Gon173 commented on ISTbd-22/Kuchina A. A/lab8.1/list.h
> +    }
У вас реализован просмотр списка, как для однонаправленного. Поиск по индексу можно сократить в 2 раза, если  определять, как быстрее просматривать, с конечного или с начального узла.

2020-12-18 19:22 UTC, Qui-Gon173 commented on ISTbd-22/Kuchina A. A/lab8.1/list.h
> +    };
Аналогичное замечание про переход по списку. Определяйте по индексу, как быстрее дойти до позиции вставки(с конца или с начала)

2020-12-18 19:22 UTC, Qui-Gon173 commented on ISTbd-22/Kuchina A. A/lab8.1/list.h
> +    };
Подобное замечание про направления)

2020-12-18 19:41 UTC, HerbalTea312 commented on ISTbd-22/Kuchina A. A/lab8.1/list.h
> +    };
Поняла вас, поправлю в ближайшее время :3

2020-12-18 22:02 UTC, HerbalTea312 commented on ISTbd-22/Kuchina A. A/lab8.1/list.h
> +    };
Надо бы вообще отдельную функцию воткнуть для поиска элемента по индексу, чтоб много строчек не занимало

2020-12-19 19:00 UTC, Qui-Gon173 approved these changes
Зачтено

2020-12-19 19:00 UTC, merged