Ushkova A lab 8.2
Qui-Gon173/AiSD-2020 pull request #272
Opened 2020-12-18 16:14 UTC by U-Aleksandra

2020-12-18 19:37 UTC, Qui-Gon173 requested changes

2020-12-18 19:37 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/List.h
> +    unsigned int avarage();
average

2020-12-18 19:37 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/List.h
> +   }
А если элемент не найдет, что вернет оператор?

2020-12-18 19:37 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/List.h
> +}
Чем метод отличается от push_back?

2020-12-18 19:38 UTC, Qui-Gon173 commented
Приведите в порядок наименование методов/полей. Где-то с большой, где-то с маленькой буквы. Есть использование транслита

2020-12-22 20:05 UTC, Qui-Gon173 requested changes
Также разделите объявление от реализации. В `.h` только объявление, в `.cpp` только реализация.

2020-12-22 20:05 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/List.h
> +   }
![image](https://user-images.githubusercontent.com/3108341/102928121-a4388600-44b1-11eb-8a35-24749ea6899c.png)
Почему?)

2020-12-22 20:05 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/List.h
> +        int Size;
Size все также с большой буквы

2020-12-22 20:05 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/List.h
> +    void poisk_index(unsigned int value);
Транслит...

2020-12-23 17:36 UTC, Qui-Gon173 requested changes
Учтите данные замечания. Если вы что-то не понимаете, лучше спросите, не стесняйтесь

2020-12-23 17:36 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/List.cpp
> +void List::poiskIndex(unsigned int value)
Вы оставили транслит, выберите одно из названий: searchByIndex или findByIndex.

2020-12-23 17:36 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/main.cpp
> +    auto value=(*container)[3];
Вопрос был именно про exception: Почему он возникает. Он не должен возникать, потому что это ломает программу.
![image](https://user-images.githubusercontent.com/3108341/102928121-a4388600-44b1-11eb-8a35-24749ea6899c.png)
Я вам писал про оператор [ ] и именно из-за этого возникает исключение. Подумайте, что нужно сделать, чтобы оператор отрабатывал правильно.

2020-12-25 14:13 UTC, U-Aleksandra commented on ISTbd-22/Ushkova A. S/lab8.2/main.cpp
> +    auto value=(*container)[3];
Я не могу понять, в чем здесь проблема. Проверяю с помощью exe-файла, а там у меня все работает. 
<img width="517" alt="prog" src="https://user-images.githubusercontent.com/73467714/103136721-450a8980-46dc-11eb-85e6-12b3bfc58cc9.png">

2020-12-28 18:52 UTC, Qui-Gon173 commented on ISTbd-22/Ushkova A. S/lab8.2/main.cpp
> +    auto value=(*container)[3];
Смотрите, если запустить программу и вывести полученное значение по 2 индексу, будет какая-то бабара, ведь по коду добавлялись только `1` и `12`.
![image](https://user-images.githubusercontent.com/3108341/103236538-95911980-495e-11eb-8a05-bc808274528d.png)
![image](https://user-images.githubusercontent.com/3108341/103236628-c6714e80-495e-11eb-9810-2b63182345fb.png)
Если взять значение по 3 индексу, будет ошибка, которую я вам показывал.
Проблема в том, что у вас оператор индекса не возвращает значения, если элемент по индексу не найден. 
Проблема решается в 1 строчку, подумайте какой.

2020-12-28 19:17 UTC, Qui-Gon173 commented
Ладно, думаю хватит вас мучить. Засчитана лаба

2020-12-28 19:17 UTC, Qui-Gon173 approved these changes

2020-12-28 19:18 UTC, merged