УБЕРИТЕ ЭТО ОТ МЕНЯ!
Qui-Gon173/AiSD-2020 pull request #279
Opened 2020-12-19 21:13 UTC by bastep-ulstu

УСТАЛ.......

2020-12-22 19:37 UTC, Qui-Gon173 requested changes
Еще замечание. Вся реализация классов написана в `.h` файлах. Разделите объявление от реализации(объявление в `.h`/`.hpp`, реализация в `.cpp`)

2020-12-22 19:37 UTC, Qui-Gon173 commented on ISTbd-22/Tagashev I.I/lab8.2/ArifmProgression.h
> +		_state = new int(++++_multiplier);
А это точно геометрическая прогрессия?) больше похоже на арифметическую прогрессию x+2?)

2020-12-22 19:37 UTC, Qui-Gon173 commented on ISTbd-22/Tagashev I.I/lab8.2/Node.h
> +	}
А вам нужен конструктор по умолчанию? если вы используете узел, то только со значением.

2020-12-23 09:29 UTC, bastep-ulstu commented on ISTbd-22/Tagashev I.I/lab8.2/ArifmProgression.h
> +		_state = new int(++++_multiplier);
Так у меня арифметическая)))
ГЕОМЕТРИЯ ЗЛОО

2020-12-26 15:39 UTC, Qui-Gon173 approved these changes
Зачтено

2020-12-26 15:39 UTC, merged