Sedykh-N-V-lab-8.1
Qui-Gon173/AiSD-2020 pull request #280
Opened 2020-12-20 13:30 UTC by SeNat07

2020-12-22 19:45 UTC, Qui-Gon173 requested changes
Также у вас нет файла для объявления класса (`.h` или `.hpp`). Разделите реализацию и объявление.

2020-12-22 19:45 UTC, Qui-Gon173 commented on ISTbd-22/Sedykh N. V/lab8.1/Stack.cpp
> +	std::vector<float> stackElements;
Реализовывать стек на векторе конечно хитро, но так не пойдет. Выберите один базу из вариантов:
1. На массиве - нужно управлять расширением\сужением массива и сохранять индекс последнего добавленного значения
1. На кастомном классе Node - В Node указывается ссылка на предыдущий элемент и значение узла. В классе Stack храниться только ссылка на "верхнюю" ноду.

2021-01-13 04:23 UTC, Qui-Gon173 commented
21 день лаба в доработке. Если у вас есть вопросы, спросите

2021-01-14 15:47 UTC, Qui-Gon173 requested changes
Есть замечания, исправьте их. Они мелкие. После исправления лабу зачту.

2021-01-14 15:47 UTC, Qui-Gon173 commented on ISTbd-22/Sedykh N. V/lab8.1/Stack.cpp
> +	std::vector<float> stackElements;
У вас остался предыдущая версия стека. Лучше ее удалить

2021-01-14 15:47 UTC, Qui-Gon173 commented on ISTbd-22/Sedykh N. V/lab8.1/Stack.h
> +
Новую реализацию лучше перенести в cpp файл, на место старой

2021-01-14 17:02 UTC, Qui-Gon173 commented
Хотя ладно, зачтено

2021-01-14 17:02 UTC, Qui-Gon173 approved these changes

2021-01-14 17:03 UTC, merged

2021-01-14 17:05 UTC, SeNat07 commented
О, спасибо)