Lab1
Qui-Gon173/AiSD-2020 pull request #29
Opened 2020-10-28 21:42 UTC by bastep-ulstu

cpp + отчёт

2020-10-29 13:05 UTC, Qui-Gon173 requested changes

2020-10-29 13:05 UTC, Qui-Gon173 commented on ИСТбд-22/Tagashev I.I/lab1/lab1/Source.cpp
> +}
Что вернет функция, если искомый элемент не найден?

2020-10-29 13:05 UTC, Qui-Gon173 commented on ИСТбд-22/Tagashev I.I/lab1/lab1/Source.cpp
> +	vivod(count, array);
Сохраняйте файлы в UTF-8

2020-10-29 15:14 UTC, v01d-gh commented on ИСТбд-22/Tagashev I.I/lab1/lab1/Source.cpp
> +	vivod(count, array);
@bastep-ulstu https://discord.com/channels/752760874007003166/752760874007003169/770549357736493076

2020-10-29 18:17 UTC, bastep-ulstu commented on ИСТбд-22/Tagashev I.I/lab1/lab1/Source.cpp
> +}
Если элемент не найден будет надпись об ошибке, но это реализовано в исправленном cpp.

2020-10-30 04:52 UTC, Qui-Gon173 approved these changes
Засчитано

2020-10-30 04:53 UTC, merged