Iskhakov E A, lab1+lab2
Qui-Gon173/AiSD-2020 pull request #30
Opened 2020-10-28 21:52 UTC by MrEdwardis

Сделал сразу 1-ю и 2-ю лабы. Выкладываю main.cpp и отчёты.

2020-10-29 11:05 UTC, Qui-Gon173 commented
По отчету вопросов нет.

2020-10-29 13:04 UTC, Qui-Gon173 requested changes

2020-10-29 13:04 UTC, Qui-Gon173 commented on ИСТбд-22/Iskhakov E A/lab1+lab2/main.cpp
> +}
Если передать в функцию элемент, которого нет в массиве, программа зациклится

2020-10-29 13:04 UTC, Qui-Gon173 commented on ИСТбд-22/Iskhakov E A/lab1+lab2/main.cpp
> +	return 0;
Сохраняйте файлы в кодировке UTF-8. Гит похоже не работает с Windows-1251.

2020-10-29 15:11 UTC, v01d-gh commented on ИСТбд-22/Iskhakov E A/lab1+lab2/main.cpp
> +	return 0;
@MrEdwardis 
я, кстати, кидал в дискорде скрипт, чтобы поменять кодировку для всех файлов проекта. 
![image](https://user-images.githubusercontent.com/20192008/97592775-75a2af80-1a1a-11eb-8b02-2f62a671895e.png)

2020-10-29 17:07 UTC, MrEdwardis commented on ИСТбд-22/Iskhakov E A/lab1+lab2/main.cpp
> +	return 0;
На самом деле не знаю, как пользоваться скриптом)
По мне так проще закинуть в Notepad++ и сделать преобразование в utf-8 :)

2020-10-29 17:10 UTC, v01d-gh commented on ИСТбд-22/Iskhakov E A/lab1+lab2/main.cpp
> +	return 0;
но ведь гайд... если питон есть, кидаешь скрипт в папку и пишешь в консоли, как на скрине/в дискорде

2020-10-29 17:11 UTC, MrEdwardis commented on ИСТбд-22/Iskhakov E A/lab1+lab2/main.cpp
> +	return 0;
Не, на пАЙтоне (ыыы) пока не прогал.

> но ведь гайд... если питон есть, кидаешь скрипт в папку и пишешь в консоли, как на скрине/в дискорде

2020-10-30 04:55 UTC, Qui-Gon173 approved these changes
Засчитано

2020-10-30 04:55 UTC, merged