Doronkin A.N/lab1
Qui-Gon173/AiSD-2020 pull request #36
Opened 2020-10-29 15:29 UTC by Letov1337

2020-10-30 05:02 UTC, Qui-Gon173 requested changes
Все хорошо, вопросов по заданию нет. Перенесите вашу папку с лабами в ISTbd-22. У некоторых g++ работает плохо с кириллицей поэтому задания теперь будут жить там.

2020-10-30 10:16 UTC, Letov1337 commented
Перенес в папку ISTbd-22.

2020-10-31 08:51 UTC, Qui-Gon173 commented
Вы не удалили файлы из ИСТбд-22

2020-10-31 11:54 UTC, Qui-Gon173 approved these changes
Засчитано

2020-10-31 11:54 UTC, merged