Osipov lab1
Qui-Gon173/AiSD-2020 pull request #42
Opened 2020-10-30 05:33 UTC by KirillOsipov

2020-10-30 05:45 UTC, Qui-Gon173 requested changes
По коду есть мелкое замечание к наименованию.
По отчету нет вопросов. Но по коду вы выполняли еще 2 лабу. Добавьте отчет по 2 лабе и обе будут засчитаны.

2020-10-30 05:45 UTC, Qui-Gon173 commented on ИСТбд-22/Осипов К.С/lab1/main.cpp
> +void BubbleSort(int *x, int size)
Назовите массив в соответствии требованиям

2020-10-30 05:45 UTC, Qui-Gon173 commented on ИСТбд-22/Осипов К.С/lab1/main.cpp
> +    return found ? middle : -1;
Молодцом, воспользовались тернарником)

2020-10-30 05:45 UTC, Qui-Gon173 commented on ИСТбд-22/Осипов К.С/lab1/main.cpp
> +int BinarySearch(int *x, int size, int key)
Аналогичное замечание к наименованию массива

2020-10-30 05:45 UTC, Qui-Gon173 commented on ИСТбд-22/Осипов К.С/lab1/main.cpp
> +        arr[i] = MIN_ELEM + rand() % (MAX_ELEM - MIN_ELEM);
Хорошая идея реализовать заполнение массива рандомными значениями)

2020-10-30 05:49 UTC, Qui-Gon173 commented
Также перенесите вашу папку с лабами в ISTbd-22. У некоторых g++ работает плохо с кириллицей поэтому задания теперь будут жить там.
В следующий раз именуйте ветку по требованиям. (Латиницей, с указанием номера лабы. Смотрите требования.)

2020-10-30 11:44 UTC, KirillOsipov commented on ИСТбд-22/Осипов К.С/lab1/main.cpp
> +void BubbleSort(int *x, int size)
Здравствуйте, я исправил замечания и добавил отчёт ко 2-ой лабораторной

2020-10-31 08:54 UTC, Qui-Gon173 commented
> Также перенесите вашу папку с лабами в ISTbd-22. У некоторых g++ работает плохо с кириллицей поэтому задания теперь будут жить там.
> В следующий раз именуйте ветку по требованиям. (Латиницей, с указанием номера лабы. Смотрите требования.)
Вы не перенесли вашу папку в ISTbd-22.

2020-11-19 18:05 UTC, merged