lab2-EgorovIE
Qui-Gon173/AiSD-2020 pull request #55
Opened 2020-10-31 22:01 UTC by Doomaykaka

2020-11-02 18:43 UTC, Qui-Gon173 requested changes
Исправьте мелкие замечания. По заданию в целом вопросов нет, с логической точки зрения все сделано правильно. 
Также видел у вас 1 лабу. Вы закрыли пул реквест без проверки и она пока не проходила проверку. Но в ветке она у вас есть.
Также замечания по наименованию ветки, именуйте латиницей и именуйте по шаблону. Каждую лабу делайте в новой ветке. Со следующей лабы придерживайтесь данного правила.
Перенесите папку с вашими лабами из `ИСТбд-22` в `ISTbd-22`(Создайте каталок  `ISTbd-22` и перенесите в него. Некоторые переименовывают корневую папку и тянут за собой задание всех в группе).

2020-11-02 18:43 UTC, Qui-Gon173 commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +int vvod(int nm, int *arr)
Метод лучше назвать input или input_data

2020-11-02 18:43 UTC, Qui-Gon173 commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +    return(nm,*arr);
Что делает операция `(nm,*arr)` и для чего она нужна? Ответ в комментарий к этому комментарию.

2020-11-02 18:43 UTC, Qui-Gon173 commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +int vvod(int nm, int *arr)
Для чего нужно указывать возвращаемый тип  у функции(`int`), если результат не используется?

2020-11-02 18:43 UTC, Qui-Gon173 commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +int vivod(int nm, int *arr)
По аналогии `vvod`, лучше метод назвать output или output_data

2020-11-02 18:43 UTC, Qui-Gon173 commented on ИСТбд-22/Егоров И.Е/lab2/lab2.md
> ++Работает сравнительно быстрее
Укажите точнее, сравнительно с каким методом. Вероятно вы говорили про метод пузырька, но укажите точно, с чем вы сравниваете шейкерную сортировку.

2020-11-02 18:43 UTC, Qui-Gon173 commented on ИСТбд-22/Егоров И.Е/lab2/lab2.md
> ++Сложность остается той же
Аналогичное замечание про уточнение

2020-11-02 18:43 UTC, Qui-Gon173 commented on ИСТбд-22/Егоров И.Е/lab2/lab2.md
> ++Быстрее предыдущих алгоритмов
Вот здесь сразу ясно)

2020-11-05 17:01 UTC, Doomaykaka commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +    return(nm,*arr);
Т.к. вывод я использую в разных участках кода , то я хотел для вывода использовать одну и туже функцию (аргументы меняются после сортировки), потому функция должна возвращать какое либо значение

2020-11-05 17:03 UTC, Doomaykaka commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +int vvod(int nm, int *arr)
Понял

2020-11-05 17:03 UTC, Doomaykaka commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +int vivod(int nm, int *arr)
Понял

2020-11-05 17:14 UTC, Doomaykaka commented
На счёт закрытого пула по первой лабораторной - я забыл там отчёт заменить

2020-11-05 17:26 UTC, Doomaykaka commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +    return(nm,*arr);
return (nm,*arr) возвращает число элементов и сами элементы

2020-11-05 17:32 UTC, Doomaykaka commented on ИСТбд-22/Егоров И.Е/lab2/lab2.cpp
> +int vvod(int nm, int *arr)
Мы результат функций обратно передаём в main , а потом отправляем на сортировку (результат этой функции мы используем)

2020-11-06 11:10 UTC, closed without merging