[Hodarev-D-A] Fixed README.md for lab6.
Qui-Gon173/AiSD-2020 pull request #68
Opened 2020-11-02 21:17 UTC by Juggernauff

Недочёты исправлены.

2020-11-03 07:26 UTC, Qui-Gon173 requested changes
А где сами изменения по 6?)

2020-11-03 07:29 UTC, Qui-Gon173 commented
Давайте свяжемся сегодня вечером. Не очень хорошо получается работать в одной ветке, нужно будет переходить на 1 ветку на лабу.

2020-11-03 08:20 UTC, Juggernauff commented
Видимо я плохо понял, я вроде попытался что-то в ветке изменить, но ... :D

2020-11-05 06:12 UTC, Qui-Gon173 commented
В коммите не вижу изменений по 6 лабе) свяжитесь со мной через любой контакт, посмотрим, что можно сделать)

2020-11-05 18:21 UTC, Juggernauff commented
Жду ответа в discord)

2020-11-15 08:48 UTC, closed without merging